models/product.py
"""
This file have the model
for add a product in the database.
"""

from enum import unique
from helpers.db import db


class PriceInvalid(TypeError):
    """
    Execption class in case
    the price for save in the database
    not is valid.
    """

    pass


class Products(db.Model):
    """
    Model for the tabel of products
    """

    # values
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    price = db.Column(db.Integer, unique = False)
    date = db.Column(db.String(100))

    def __init__(self, name: str, price: int, date: str) -> None:
        # validating the price
        if type(price) not in [int]:
            raise PriceInvalid('The price passed for parameter not is valid.')

        self.name = name
        self.price = price
        self.date = date

models/settings.py
"""
This module have the model
for the settings.
"""

class InvalidSetting(TypeError):
  """
  In case the setting passed for
  parameter is invalid.
  """
  pass

class Settings:
  """
  Model for the settings
  with properties.

  view_style for the view of products.

  """

  def __init__(self, view_style:str) -> None:
    if type(view_style) not in [str]:
      raise InvalidSetting('The view_style passed for parameter must be a string.')

    self.view_style = view_style
      

app.py
"""
This is the file, for some configurations
and hooks for the server. For execute the server
execute the file index.py
"""

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from routes.products import products
from config import CONFIG

# creating the server
server = Flask(__name__)

# settings
server.config['SQLALCHEMY_DATABASE_URI'] = CONFIG['SQLITE_CONNECTION']
server.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
server.secret_key = 'mysecretkey'

# database initilization
SQLAlchemy(server)

# using routes
server.register_blueprint(products)

routes/products.py
"""
This file have the routes
to use in the server.
"""


from crypt import methods
from flask import (
    Blueprint,
    render_template,
    request,
    url_for,
    redirect,
    flash
)
from helpers.db import db
from models.product import Products
from models.settings import Settings
from helpers.utils import get_values_to_add, get_values_to_update, change_settings, validate_view_style

# routes
products = Blueprint('products', __name__)

# settings of the view
settings = Settings(
    view_style='All.'
)


@products.route('/')
def home():
    """
    Initial route,
    consult alls the products for show.
    """

    # getting the product for pass into page
    products = Products.query.all()
    # validating the style for the view of product
    view_style = settings.view_style
    new_products = validate_view_style(products, view_style)

    return render_template('index.html', products=new_products)


@products.route('/add', methods=['POST'])
def add_product():
    """
    Route for add a new product.
    """

    # getting the creating a product
    name, price, date = get_values_to_add()
    product = Products(name, price, date)

    db.session.add(product)  # adding
    db.session.commit()

    flash('Product Saved Successfully.')

    return redirect(url_for('products.home'))


@products.route('/update/<id>', methods=['GET', 'POST'])
def update_product(id):
    """
    Route for update a product.
    Id is required for update.

    If the method is GET, return the page, with
    the formulary. If the method is POST, update
    the product in the database.
    """

    id = int(id)

    # changeing values and adding
    product = Products.query.filter_by(id=id).first()

    if request.method == 'GET':
        return render_template('update-product.html', product=product)
    elif request.method == 'POST':
        # getting new values
        new_name, new_price, new_date = get_values_to_update()
        product.name = new_name
        product.price = new_price
        product.date = new_date
        db.session.add(product)
        db.session.commit()

        flash('Product Updated Successfully.')

        return redirect(url_for('products.home'))

    else:
        return 'Method not is available.'


@products.route('/delete/<id>')
def delete_product(id):
    """
    Route for delete a product,
    recived the id for the product.

    """
    # converting
    id = int(id)

    productFound = Products.query.filter_by(id=id).first()
    db.session.delete(productFound)  # removing
    db.session.commit()

    flash('Product Deleted Successfully.')

    # redirect
    return redirect(url_for('products.home'))


@products.route('/change-settings', methods=['GET', 'POST'])
def change_settings_route():
    """
    Return the page
    with the settings.
    Running with GET and POST
    method for change the setting.
    """

    global settings
    # in case is get
    if request.method == 'GET':
        return render_template('settings.html', settings=settings)

    elif request.method == 'POST':
        new_view_style = request.form['view-style']
        change_settings(settings, new_view_style)
        return redirect(url_for('products.home'))


@products.route('/about')
def about():
    """
    Route for render
    the about page
    """

    return render_template('about.html')

templates/about.html
{% extends 'layout.html' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/about.css') }}">
<section class="bg-dark p-3 about">
  <p class="text-white text-center">
    This is a web appliaction for manage products.
  </p>
</section>
{% endblock %}

templates/index.html
<!-- PRINCIPAL PAGE -->
{% extends 'layout.html' %}
{% block content %}
<!-- VIEW TO SAVE -->
<div class="view">
    {% include 'partials/_message.html' %}

    {% include 'partials/_formAddProduct.html' %}
</div>


<!-- VIEW PRODUCTS -->
<div class="view-products">
    {% if products %}
    {% for product in products %}
    <div class="p-3 product">
        <div>
            <h4 class="text-white text-start">Name: {{ product.name }}</h3>
            <h4 class="text-white">Price: ${{ product.price }}</h4>
            <h5 class="text-white">
                Date:
                <span class="text-info">{{ product.date }}</span>

            </h5>
        </div>

        <!-- ACTIONS BUTTONS -->
        <div class="actions-buttons">
            <a class="btn btn-danger mx-2 delete-button" href="{{ url_for('products.delete_product', id = product.id) }}">Delete</a>
            <a class="btn btn-success mx-2 update-button" href="{{ url_for('products.update_product', id = product.id) }}">Update</a>
        </div>

    </div>
    {% endfor %}
    {% else %}
    <h4 class="text-white text-center">No products.</h4>
    {% endif %}
</div>

<!-- SCRIPT ESPECIAL HERE -->
<script src="{{ url_for('static', filename = 'js/app.js') }}" type="module"></script>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Products App</title>
    <!-- FAVICON -->
    <link rel="shortcut icon" href="{{ url_for('static', filename = 'img/favicon.ico') }}" type="image/x-icon">
    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/bootstrap.min.css') }}">
    <!-- CUSTOM STYLE -->
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/custom.css') }}">
</head>

<body>

    {% include 'partials/_nav.html' %}

    <!-- CONTAINER -->
    <div class="container" id="principal-container">
        {% block content %} {% endblock %}
    </div>

    {% include 'partials/_footer.html' %}

    <!-- SCRIPTS -->
    <script src="{{ url_for('static', filename = 'js/bootstrap.bundle.min.js') }}"></script>

</body>

</html>

templates/partials/_footer.html
<!-- FOOTER TO USE -->
<footer id="principal-footer">
  <div class="p-2">
    <p class="text-white text-center">2022</p>
    <p class="text-white text-center">Website made for Daniel Yanes.</p>

  </div>

  <div class="mx-auto text-center links">
    <a class="btn btn-primary w-50 my-1" href="https://github.com/EduardYan/" target="_blank">My Github</a>
    <a class="btn btn-dark w-50 my-1" href="mailto:eduarygp@gmail.com">Contact Me</a>
  </div>

</footer>

templates/partials/_formAddProduct.html
<!-- FORMULARY TO USE 
  FOR ADD A NEW PRODUCT -->
<form class="card" action="{{ url_for('products.add_product') }}" method="POST">
  <div class="card-header">
    <!-- TITLE -->
    <h3 class="text-white text-start" id="title-product">Add a New Product</h3>

  </div>
  <div class="card-body">
    <label class="text-white" for="name">Product Name</label>
    <div class="form-control">
      <input type="text" id="name" name="productName" autofocus>
    </div>

    <label class="text-white" for="price">Product Price</label>
    <div class="form-control">
      <input class="text-center" type="number" id="price" name="productPrice">

    </div>

    <label class="text-white" for="date">Date</label>
    <div class="form-control">
      <input class="text-center" type="date" id="date" name="productDate">

    </div>

    <!-- SAVE BUTTON -->
    <div class="w-100 mx-auto text-center mt-4 mb-3">
      <button class="btn btn-success w-50" type="submit">Save</button>
    </div>

  </div>

</form>

templates/partials/_formUpdateProduct.html
<!-- FORMULARY TO USE 
  FOR UPDATE A NEW PRODUCT -->
<form class="card" action="{{ url_for('products.update_product', id = product.id) }}" method="POST">
  <div class="card-header">
    <!-- TITLE -->
    <h3 class="text-white text-start" id="title-product">Update it!</h3>

  </div>
  <div class="card-body">
    <label class="text-white" for="newName">New Product Name</label>
    <div class="form-control">
      <input type="text" id="newName" name="newProductName" autofocus value="{{ product.name }}">
    </div>

    <label class="text-white" for="newPrice">New Product Price</label>
    <div class="form-control">
      <input type="number" id="newPrice" name="newProductPrice" value="{{ product.price }}">
    </div>

    <label class="text-white" for="newDate">Date</label>
    <div class="form-control">
      <input type="date" id="newDate" name="newProductDate" value="{{ product.date }}">

    </div>

    <!-- UPDATE BUTTON -->
    <div class="w-100 mx-auto text-center mt-4 mb-3">
      <button class="btn btn-success w-50" type="submit">Update</button>
    </div>

  </div>

</form>

templates/partials/_message.html
<!-- MODEL FOR EACH MESSAGE -->
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

templates/partials/_nav.html
<!-- NAVIGATION -->
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/nav.css') }}">
<nav class="navbar navbar-expand-md navbar-dark">
    <div class="container">

        <a class="navbar-brand navbar-title" href="{{ url_for('products.home') }}">Products App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('products.home') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('products.about') }}" }>About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('products.change_settings_route') }}" }>Settings</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/settings.html
{% extends 'layout.html' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/settings.css') }}">

<form class="card" action="{{ url_for('products.change_settings_route') }}" method="POST">
  <div class="card-header">
    <h2 class="text-white text-center">Settings</h2>
  </div>
  <div class="card-body">
    <div class="form-control">
      <label class="h5 text-white" for="view-style">View of products for see.</label>
      <select class="form-select my-3 w-50" name="view-style" id="view-style">
        <!-- OPTIONS TO USE -->
        <option value="{{ settings.view_style }}" selected>{{ settings.view_style }}</option>
        <option value="All.">All.</option>
        <option value="Mayor or equal to 100.">Mayor or equal to 100 dolars.</option>
        <option value="Mayor or equal to 300.">Mayor or equal to 300 dolars.</option>
        <option value="Mayor or equal to 500.">Mayor or equal to 500 dolars.</option>
        <option value="Mayor or equal to 1000.">Mayor or equal to 1000 dolars.</option>
      </select>

    </div>
    <div class="mx-auto text-center my-3" id="save-button-settings">
      <button class="btn btn-success" type="submit" id="">Save</button>
    </div>
  </div>
</form>


{% endblock %}

templates/update-product.html
<!-- PAGE FOR UPDATE A USER -->
{% extends 'layout.html' %}


{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/update.css') }}">
{% include 'partials/_formUpdateProduct.html' %}
{% endblock %}